language: node_js
before_install: 
  - nvm install node
  - npm install -g browserify
  - npm install -g uglifycss
  - npm install -g uglifyjs
install: npm install
script: true
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  commiter-from-gh: true
  on:
    branch: master
